### ISSUE TITLE
Extract pr_processor version into common place

### ISSUE THREAD

**Issue by spyrkob** [jboss-set/zeus#82]
Currently pr_processor version is defined in both vars.yaml and roles/pr_processor/defaults/main.yml this should be only in single place

**Comment by soul2zimate** [comment]
Fixed by https://gitlab.cee.redhat.com/jboss-set/zeus-vars/-/commit/8d16a4f817deed5ea39bd77c4e220d38cf904be2 and https://github.com/jboss-set/zeus/commit/ca1ebbd10fb257a3f86df614c359565b87497dd4
